name: Daily Crypto Investment Analysis

on:
  schedule:
    - cron: "0 1 * * *"  # Runs at 01:00 UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Use v2 or later
      with:
        persist-credentials: true  # Allows the bot to use the token

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run investment analysis script
      run: python main.py

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add *.json
        git commit -m "Add daily crypto analysis results"
        git push

    - name: Upload price and yield files
      uses: actions/upload-artifact@v4
      with:
        name: crypto-analysis-files
        path: |
          *.price.json
          *.yield.json
